config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name ,presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
     @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
     params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
     params.require(:dose).permit(:description, :ingredient_id)

  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
 <div class="container">
    <div class="text-center">
    <h1>Cocktail Paradise</h1>
    <%= link_to "Nouveau Cocktail", new_cocktail_path(@cocktails), class: "btn btn-primary"%>
  </div>
    <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="card col-xs-4 text-center">
        <h2><%= cocktail.name %></h2>
        <%= link_to "Details du cocktail", cocktail_path(cocktail), class: "btn btn-primary", method: :get %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Ajouter le cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="text-center">
    <h1><%=@cocktail.name%></h1>
    <% @cocktail.doses.each do |dose| %>
      <p><%= dose.description %></p>
      <p><%= dose.ingredient.name %></p>
    <% end %>
    <%= link_to "Ajouter un ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
    <%= link_to "retour", cocktails_path(@cocktails), class: "btn btn-primary" %>
  </div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [ @cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.submit "Valider", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>